spring:
  application:
    name: EMS-SpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: pgadmin
    password: passw0rd123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis

server:
  port: 8081

jms:
  queue: emsService
  otp:
    queue: otpService
  login:
    queue: otpLogin

ems:
  messageQueue: ems.messageQueue